### ISSUE TITLE
Bug in menu dropdown

### ISSUE THREAD

**Issue by lvieira268** [jpvalery/portfolio#122]
**Describe the bug**
The dropdown is hidden under the image cards

**Screenshots**
![image](https://user-images.githubusercontent.com/10107703/219821570-3eb07e9a-6ad5-4798-a095-0285011db5d6.png)

**Desktop
- Google Chrome Version 110.0.5481.77 (Official Build) (64-bit)

**Comment by jpvalery** [comment]
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/4112343/226215387-2130dd50-a243-4244-a3b9-b958b13d9d95.png">

fixed in ba57935
