### ISSUE TITLE
replicating Contentful schema

### ISSUE THREAD

**Issue by RohanSasne** [jpvalery/portfolio#125]
Can we have the screenshot of the schema used on Contentful ? I am having some problems in replicating the schema :)

**Comment by RohanSasne** [comment]
@jpvalery , Pinging you for your assistance :)

**Comment by jpvalery** [comment]
See readme: 

> [Notes](https://github.com/jpvalery/portfolio#notes)
> 
>     Code can be used as a reference for other projects but won't work out of the box without replicating Contentful schema.
> 
>     Inspire yourself and tinker all you want, just give credit and don't do a mindless copy-paste.
