### ISSUE TITLE
WebpackError: TypeError: props.tags.map is not a function

### ISSUE THREAD

**Issue by jpvalery** [jpvalery/portfolio#2]
This is leaving me scratching my head. Gatsby develop does run without issues, but Gatsby build generates this error: 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/4112343/51363370-a9128500-1aa5-11e9-81bc-f90cc3aed340.png">

`<List>
          {props.tags.map(tag => (
            <Tag key={tag.id}>
              {tag.title}
            </Tag>
          ))}
        </List>`

**Comment by iammatthias** [comment]
Does every post have tags in Contentful?

**Comment by jpvalery** [comment]
I think they did - but back in January I decided to just ignore this since this wasn't a feature that I particularly wanted to have :D
