### ISSUE TITLE
  TypeError: Cannot read property 'allContentfulExtendedGallery' of undefined

### ISSUE THREAD

**Issue by glaucopater** [jpvalery/portfolio#98]
**Describe the bug**
Error "Cannot read property 'allContentfulExtendedGallery' of undefined" is raised during dev/build.
I looked at the previous issue https://github.com/jpvalery/portfolio/issues/1 creating content, but this is still not working,  :(

**To Reproduce**
1. Running setup (yarn run setup or gatsby build)

My local setup for Contentful is currently working with GCN.

**Comment by jpvalery** [comment]
Sorry but I don't offer support on this project.
